<template>
    <div class="flex flex-col lg:flex-row">
        <div class="panel-one w-full h-full lg:h-screen overflow-hidden">
            <div v-for="image in images" :key="image.id">
                <ImageFull :image="image"/>
            </div>
        </div>
        <div class="panel-two w-full h-full lg:min-h-screen lg:max-h-screen lg:overflow-scroll p-5 sm:p-10 lg:p-20">
            <h2 class=" font-black uppercase">President´s welcome message title</h2>
            <p class=" pb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi congue mi vel lorem pellentesque efficitur. Vivamus id elit dolor. Vestibulum lacinia sem vel vestibulum lobortis. Etiam auctor mattis ligula, a eleifend nibh fermentum vel. Nam cursus turpis vitae tincidunt ullamcorper. Ut eget vestibulum mauris, quis blandit risus. Donec euismod dictum nisl vel mattis.</p>
            <p class=" pb-5">Sed varius venenatis orci, non mattis magna mollis non. Sed in imperdiet sapien, vitae venenatis orci. Fusce gravida sodales aliquam. Aenean facilisis quis metus at laoreet. Curabitur eu nunc erat. Duis nec ante finibus, luctus ligula ut, tristique ipsum. In hac habitasse platea dictumst.</p>
            <p class=" pb-5">Etiam elementum vehicula nulla, sit amet semper sapien venenatis a. Pellentesque nec interdum ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam rhoncus ex ut gravida dignissim. Ut ullamcorper eleifend massa in cursus. Mauris non nibh sodales, eleifend dolor vitae, vulputate purus. Proin velit quam, ultricies ac est at, tristique elementum orci. Pellentesque eu lorem non nibh mollis pharetra. Donec dignissim congue ante, eget facilisis lectus viverra nec. Phasellus pellentesque quam sapien, vitae aliquet nulla tristique nec.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p class=" pb-5">Nulla convallis, turpis vel rhoncus gravida, diam risus vestibulum augue, ac scelerisque erat libero sit amet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Nulla facilisi. Aliquam bibendum iaculis fringilla. Aliquam eu cursus augue. Curabitur a facilisis leo, non hendrerit felis. In et convallis ligula. Pellentesque aliquam nisi vitae nulla consequat, quis accumsan purus pulvinar. Donec facilisis euismod nulla nec tristique. Vivamus sed libero vulputate, semper turpis vitae, dapibus ligula.</p>
            <p>Aenean quis cursus lorem. Sed et risus vitae ante semper auctor. Cras sit amet lorem enim. Proin hendrerit diam neque, ac facilisis orci rhoncus in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pulvinar turpis nec neque posuere consectetur. Sed sit amet est eu ligula volutpat interdum id a magna. Ut quis egestas arcu. Cras luctus, purus at ornare auctor, nunc quam egestas velit, in posuere ligula risus sit amet justo. Ut non dapibus felis. Suspendisse in magna nec ante cursus hendrerit nec ac quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
        </div>
    </div>
</template>

<script>
export default {
  data() {
    return {
      images: [
        {
          id: 1,
          photo:
            'https://cdn.pixabay.com/photo/2021/11/11/13/08/leopard-6786267__340.jpg',
        }
      ],
    };
  },
};

</script>

<style scoped>

.panel-one {
    @media (min-width: 1024px) {
        max-width: 50%;
    }
}

</style>